### ISSUE TITLE
Linker cannot find giza library if the directory contains a blank character

### ISSUE THREAD

**Issue by BjoernBinaer** [danieljprice/giza#32] opened 2021-05-12 09:43 UTC
While installing giza for splash, I found an issue with the build system. Unfortunately I don't know where this bug comes from, but you can try to recreate it by setting up the following:
```bash
mkdir Test\ Directory
cd Test\ Directory
git clone https://github.com/danieljprice/giza.git
cd giza
./configure && make 
```
The output I get looks something like the following:
```bash
  [ ... ]
  CCLD     libgiza.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       libcpgplot_la-giza-cpgplot.lo
  CCLD     libcpgplot.la
/usr/bin/ld: cannot find -lgiza
collect2: error: ld returned 1 exit status
```
However, if you repeat the same test and change the name of the directory to not include a blank symbol, it just works fine. Again, I don't know whether this is an explicit issue on your side or some quirk of the build system with automake, make and gcc. 

Tested on:
Manjaro Linux Ornara 21.0.4
automake (GNU automake) 1.16.3
GNU Make 4.3
gcc (GCC) 10.2.0

**Comment by danieljprice** [comment] 2021-05-17 00:08
thanks for flagging this, looks like the directory name needs to be in quotes somewhere in the Makefile, this is probably an issue with the splash Makefile rather than with giza.

**Comment by danieljprice** [comment] 2021-06-18 04:24
I could reproduce this, but closing as unfixable, apparently it is a fundamental flaw in automake: https://stackoverflow.com/questions/12883599/handling-whitespaces-in-file-names-using-autotools

apparently Gnu make itself also does not support spaces in directory names:
https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them

so I gave up on trying to fix this. Ultimately it's a one line change in the eventual Makefile, but involves manual patching after the configure step... ugh

**Closed by danieljprice** 2021-06-18 04:24 UTC
