### ISSUE TITLE
_giza_parse_string corrupts stack

### ISSUE THREAD

**Issue by olebole** [danieljprice/giza#13] opened 2018-10-30 11:54 UTC
In Debian, giza is used by the [dpuser](https://packages.debian.org/sid/dpuser) package as a pgplot replacement. Dpuser fails to build on arm64 platforms with a segmentation fault while generating the documentation with `@graph.dpuser`. This is reported as [Debian#912167](https://bugs.debian.org/912167).
The problem could be traced down to a bug in the latest giza 1.0.0. Quoting @egrimley from the bug:
> The segfault happens when `_giza_parse_string` tries to return.  The return address on the stack was corrupted by this call to `cairo_get_current_point`:
>
> https://github.com/danieljprice/giza/blob/b6c1affdd20823f973d60f06d696e35b73a9942c/src/giza-scanner.l#L206-L208
>
> If you add this assertion just before that line you should see the assertion fail:
> ```
> assert(0 <= nGlyph && nGlyph < lenstr);
> ```

**Comment by egrimley** [comment] 2018-10-31 10:48
It's a simple off-by-one error, isn't it? The "we can always do this" claim in the comment is only true if we declare `positions[lenstr + 1]` instead of `positions[lenstr]`.

**Comment by danieljprice** [comment] 2018-10-31 11:20
I think that’s the right answer here

**Comment by haavee** [comment] 2018-10-31 13:33
Hi, 

Well, that's odd ... because in theory (...) nGlyph should never be >= lenstr? Because that would imply that there are more glyphs being produced than characters in the input string. 

Worst case: input string is only simple characters, thus each character would correspond to one glyph and thus nGlyph would end up == lenstr, but only _after_ the last character had been processed.

With this I intend to say to, as far as I can tell, there is probably something else happening than a "simple off-by-one", which I would like to get on top of.

Is there any input string that reproduces the segfault?

**Comment by olebole** [comment] 2018-10-31 14:02
When running in the debugger (on arm64, since there I get the segfault), `_giza_parse_string` is called this way before:
```
Breakpoint 1, _giza_parse_string (text=text@entry=0xffffffffcce0 "0", width=width@entry=0xffffffffc920, 
    height=height@entry=0xffffffffc928, action=0xffffb77a0aa8 <_giza_action_get_size>)
    at giza-scanner.l:174
```

**Comment by haavee** [comment] 2018-10-31 14:25
OK so that's a string with only an ASCII "0" in by the looks of it?

**Comment by olebole** [comment] 2018-10-31 14:26
Yes.

**Comment by haavee** [comment] 2018-10-31 14:27
And that triggers the SIGSEGV ...

**Comment by olebole** [comment] 2018-10-31 14:29
Yes.

**Comment by egrimley** [comment] 2018-10-31 16:20
Since the Debian maintainer is here: you might want to consider adding something like `make maintainer-clean` and `( cd src && flex giza-scanner.l )` to the Debian build script, so that you *really* build from source. Then, if you want to put this fix in Debian without waiting for a new upstream release, you could just add the `+1` in `giza-scanner.l`.

**Comment by olebole** [comment] 2018-10-31 19:03
I pragmatically [fixed it in both places](https://salsa.debian.org/debian-astro-team/giza/blob/6d119b8526088e283681a2c90b388735e7842c15/debian/patches/Fix-off-by-one-declaration-bug-in-giza_scanner.l.patch).

**Comment by haavee** [comment] 2018-11-01 00:02
Right; it is an off-by-one! (phew)

The while loop counts tokens and worst case is: one token for each character and you always get an extra END token to mark, well, end-of-input. So the while loop does get executed lenstr+1 times (worst case).

**Comment by danieljprice** [comment] 2018-11-01 06:52
Thanks Harro - I’ll put out a micro release with the bug fixed

**Comment by olebole** [comment] 2018-11-01 08:06
@danieljprice just as a wish: could you have a look on some of the other (pgplot compatibiliy) issues? This would help us to gain acceptance from the perl-pgplot people.

**Comment by danieljprice** [comment] 2018-11-01 22:15
Yes, I have been talking with Karl Glazebrook (developer of perl-pgplot) directly, and asked him to put them on the issue tracker. I have successfully run the pgperl test suite and can reproduce most of the issues at least. Will try to knock them off one-by-one.

**Comment by karlglazebrook** [comment] 2018-11-02 04:42
Fantastic! Will keep an eye on this

- Karl

**Comment by haavee** [comment] 2018-11-02 08:41
Is that list of issues available somewhere?

**Comment by olebole** [comment] 2018-11-02 08:42
@havee https://github.com/danieljprice/giza/issues

**Comment by danieljprice** [comment] 2018-11-20 00:10
new release, closing this issue

**Closed by danieljprice** 2018-11-20 00:10 UTC
